### ISSUE TITLE
Test failures related to cookie verification

### ISSUE THREAD

**Issue by dima767** [wcrowell/cas-functional-tests#1]
With a fresh clone of the latest master HEAD, and running on the command like via `gradle clean farmIntegrationTest`, 3 tests fail (screenshot attached) related to cookie verification.

![screen shot 2016-04-29 at 2 15 29 pm](https://cloud.githubusercontent.com/assets/12629/14925495/b07d64b2-0e15-11e6-933a-dff5e4e99179.png)

**Comment by wcrowell** [comment]
Dmitriy, thanks for the feedback.  Looking into this now.  Should I continue this work with the functional tests?  Will it be useful to the project?  Thanks.

**Comment by dima767** [comment]
Yes, continue (if you feel like it). This is certainly useful.

**Comment by wcrowell** [comment]
Dmitriy, can you grab a fresh clone of the latest and run: gradle clean farmIntegrationTest

I made some corrections to the assertions, and I am not getting an error.

**Comment by dima767** [comment]
Pulled the latest. Still getting ```Condition not satisfied:

cookie
|
null

``````
at CommonGebSpec.verifyCookie(CommonGebSpec.groovy:29)
at LoginSpecWithService.Correct credentials, with service, logout test(LoginSpecWithService.groovy:20)```
``````

In couple of tests (`LoginSpecWithService`, `GatewaySpec`) 

Also seeing SSL handshake exceptions in the console. Note - I DID NOT import any certs into the provided Jetty keystore. I think in order for the test suite to be usable out of the box and not depend on any environment and require any additional SSL tasks, it needs to ship with an SSL keystore already prepared with a valid cert suitable to run the entire test suite without any additional steps required.

Cheers,
D.

**Comment by wcrowell** [comment]
I am able to reproduce your issue with the cookie assertion now.  Jetty is not able to find the keystore as you have stated.  In build.gradle, I have the following properties set to set the location of the Jetty keystore:

sslKeyStorePath = './etc/jetty/keystore'
sslKeyStorePassword = 'changeit'
sslKeyManagerPassword = 'changeit'

Can you check your root folder of cas-functional-tests and see if there is an /etc/jetty folder with a keystore file in it?

Regards,

William Crowell

**Comment by dima767** [comment]
Yes, the `etc/jetty/keystore` is there.

**Comment by wcrowell** [comment]
Ok, I think I have something goofed up with the sslKeyStorePath:

sslKeyStorePath = './etc/jetty/keystore'

Looking at this now.  Thank you for your feedback.

**Comment by wcrowell** [comment]
Dmitriy,

I think I have it fixed now.  The certificate I had generated was good until March 2016 and had expired.  I also set the following two properties which ultimately fixed the issue:

```
systemProperty 'javax.net.ssl.trustStore', "${project.projectDir}/etc/jetty/keystore"
systemProperty 'javax.net.ssl.trustStorePassword', 'changeit'
```

Make sure you are using Java 1.7.  Please let me know.

Regards,

William Crowell

**Comment by dima767** [comment]
The latest HEAD of master - all tests succeed. Good job!

**Comment by wcrowell** [comment]
Thanks!  I am testing with Firefox this afternoon.  I will have some more updates probably tomorrow.  Trying to parameterize some things.

**Comment by dima767** [comment]
Keep doing what you're doing - you might just own this project and be the maintainer of the official CAS functional tests suite ;-)

Cheers,
D.

**Comment by wcrowell** [comment]
I don't mind that at all!  Glad I can help!
