### ISSUE TITLE
Consider moving this project to cas-projects

### ISSUE THREAD

**Issue by dima767** [wcrowell/cas-functional-tests#2]
And maintaining it there as part of an "official" CAS functional tests suite: https://github.com/cas-projects

**Comment by dima767** [comment]
@mmoayyed , right?

**Comment by mmoayyed** [comment]
I like it. 

Brain dump:
I would also substantially prefer if we could have tests run automatically as part of the main CAS gradle build. Maybe we could add a separate tasks in the build to have IT tests run, and then we instruct Travis to invoke it. Given that with boot now, one could have an embedded CAS server up and running very quickly, bootstrapping functional tests should be very easy to run against the running instance. 

But first things first, lets get it moved once all tests pass.
